defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: bonjo

test:
  <<: *defaults
  database: bonjo

# set these environment variables on your prod server
production:
  <<: *defaults
  database: streamer
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
